### ISSUE TITLE
More parts of speech?

### ISSUE THREAD

**Issue by MrDowntempo** [NaturalLanguagePasswords/system#6]
With a list of adverbs and verbs, and a small list of prepositions, we could generate a full memorable sentence:

Adj Noun Adverb Verb Preposition Adj Noun

Any considerations to advancing the NLP sysem thusly?

**Comment by akhepcat** [comment]
You want to be careful about hard-coding the syntax like that;  what you've done is made it extremely simple to use rule-processing to reduce the keyspace needed in hash-cracking.  This is because each of the word-spaces has a different code-count, thus we get to decrease our search space everywhere we know what codes belong to each slot.

You should have many different sentence types, so that each variation of "sentence" adds to the phrase complexity and increases the time to crack.

**Comment by NaturalLanguagePasswords** [comment]
It's difficult to include other parts of speech, given all the strange rules of grammar.
